name: Publish to edge

on:
  push:
    branches:
      - main
      - track/*

jobs:
  publish-to-edge:
    uses: canonical/operator-workflows/.github/workflows/publish_charm.yaml@fix-publish
    secrets: inherit
