# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

name: Terraform modules release
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "terraform/**"
  push:
    branches:
      - main
    paths:
      - "terraform/**"

jobs:
  terraform:
    uses: canonical/operator-workflows/.github/workflows/terraform_modules_release.yaml@efdd72c768efaca41f992322fa51a830e90f4990  # main
    permissions:
      contents: write
